name: Check Base Image

on:
  schedule:
    - cron:  '0 0 * * FRI'
  workflow_dispatch:

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Base Image Checker
        id: debian
        uses: mkumatag/container-image-updater-action@v1.0.5
        with:
          base-image: 'library/python:slim-bullseye'
          image: 'dontobi/speedflux.rpi:latest'

      - name: Trigger build
        if: steps.debian.outputs.needs-update == 'true'
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Build Container
          repo: dontobi/speedflux.rpi
          token: ${{ secrets.ACTIONS_PAT }}
