name: Check Base Image

on:
  schedule:
    - cron:  '0 0 * * FRI'
  workflow_dispatch:

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v3
        with:
          repository: 'dontobi/speedflux.rpi'
          ref: 'main'

      - name: Get and write version
        id: version
        run: |
          VERSION="$(cat .github/parameters/.version)"
          echo "mage=dontobi/speedflux.rpi:$VERSION" >> $GITHUB_ENV
          echo "base=library/python:slim-bullseye" >> $GITHUB_ENV

      - name: Docker Base Image Checker (Stable)
        id: checker
        uses: mkumatag/container-image-updater-action@v1.0.5
        with:
          base-image: '${{ env.base }}'
          image: '${{ env.image }}'

      - name: Trigger build
        if: steps.checker.outputs.needs-update == 'true'
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Build Container
          repo: dontobi/speedflux.rpi
          token: ${{ secrets.ACTIONS_PAT }}
